In [8]:
import numpy as np

- reproduce the result of a np.full by using np.ones

In [11]:
def full_Matrix(a0,a1,data):
    f=np.ones((a0,a1))
    f=f*data
    return f
print(full_Matrix(4,3,9))

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


- reproduce the result of np.zeros_like by using np.zeros

In [16]:
def zero_Like(a0):
    a1=np.zeros(np.shape(a0))
    return a1
a0=np.random.random((3,4))
print (zero_Like(a0))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


- the difference between a[1, 1:2], a[1, [1]] and a[1, 1]

In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(a[1,1:2]))
print(type(a[1,[1]]))
print(type(a[1,1]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>


As shown in the output above, the type of a[1,1] is int, which is different from array of the other two.

Well, I think the first two are the same.

- create a matrix containing the integers 0 to 11 of the shape (4, 3) and (6, 2), starting from array creation using np.arange

In [47]:
a1=np.array([[0,1,2],
            [3,4,5],
            [6,7,8],
            [9,10,11]])
a2=a1.reshape((6,2))
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

- count the total number of elements in an array by using some of the aggregation functions

In [48]:
def total_Number(a0):
    tot=1
    for i in range(np.ndim(a0)):
        tot*=a0.shape[i]
    return tot
print(total_Number(a1))

12


- Do the outer product of two vectors by calling np.outer and by broadcasting

In [70]:
a=np.array([1,2,3,4])
b=np.array([4,5,6])
#np.outer
print(np.outer(a,b))
#broadcasting
def Outer(a,b):
    a0=np.zeros((a.shape[0],b.shape[0]))
    for i in range(a.shape[0]):
        for j in range(b.shape[0]):
            a0[i,j]=a[i]*b[j]
    return a0
print(Outer(a,b))
# I wonder whether this method is broadcasting.

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]
 [16 20 24]]
[[ 4.  5.  6.]
 [ 8. 10. 12.]
 [12. 15. 18.]
 [16. 20. 24.]]


- Do a bilinear product $a^T W b$ with einsum

In [85]:
def aWb(a,W,b):
    c=np.einsum('ij,jk->ik',W,b)
    d=np.dot(a,c)
    return d
W=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=np.array([[4],[5],[6]])
print(aWb(a,W,b))

[1220]
